class Config():
    DEBUG = False
    SQL_ALCHEMY_TRACK_MODIFICATIONS = False
    
class LocalDevelopmentConfig(Config):
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite3'
    SECURITY_PASSWORD_HASH = 'bcrypt' # bcrypt is a hashing algorithm
    SECURITY_PASSWORD_SALT = 'thisissomethingsecret' # salt is a random string that is used to hash the password (save us from the rainbow table attack)
    SECRET_KEY='thisissomethingsecret' # secret key is used to sign the session cookie
    SECURITY_TOKEN_AUTHENTICATION_HEADER="Authentication-Token" # header that is used to pass the token
    CACHE_TYPE="RedisCache" # type of cache that we are using
    CACHE_DEFAULT_TIMEOUT=30 # default timeout for the cache
    CACHE_REDIS_PORT=6379 # port of the redis server
    
    WTF_CSRF_ENABLED = False # CSRF is a security feature that is enabled by default in Flask-WTF. We are disabling it for now.it only take data from the form that is generated by the server